version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - mindtracker-network

  app:
    build: .
    restart: unless-stopped    
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_CONNECTION_STRING=mongodb://mongo:27017/mindtracker
      - SESSION_NAME=mindtracker_session
      - SESSION_SECRET=${SESSION_SECRET}
      - BASE_URL=/
    networks:
      - mindtracker-network
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mindtracker-network

networks:
  mindtracker-network:
    driver: bridge

volumes:
  mongo-data: