version: '3.8'

services:
  # Node.js-application
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - mindtracker-network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_CONNECTION_STRING=mongodb://mongo:27017/mindtracker
      - SESSION_NAME=mindtracker_session
      - SESSION_SECRET=${SESSION_SECRET:-din_hemliga_nyckel_här}
      - BASE_URL=/

  # MongoDB
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mindtracker-network
    # Ingen exponerad port för säkerhet, bara tillgänglig internt
    # Om du behöver åtkomst från värdsystemet, kommentera bort:
    # ports:
    #   - "27017:27017"

networks:
  mindtracker-network:
    driver: bridge

volumes:
  mongo-data: